- key:               ton-mainnet
  name:              Ton Mainnet
  client:            ton                                 # API client name.
  server:            http://user:password@127.0.0.1:33310   # Public Ton node endpoint. IMPORTANT: full syncmode.
  height:            10000                                  # Initial block number from which sync will be started.
  min_confirmations: 11                                     # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://ton.live/landing/#{address}     # Ton does not show address information.
    transaction:     https://ton.live/landing/#{txid}
  status:            active
